### PR TITLE
Add battery heater status and command messages

### PR DESCRIPTION
**Pull request by jensenr30**

### CODE REVIEW

**Comment by tylerbrunette** [comment]
What does a fault in these messages mean?

**Comment by jensenr30** [comment]
> What does a fault in these messages mean?

I think it would be generic code that means that battery cannot carry out the heating request, or it had to terminate the operation early.

For example, if the battery sees the total pack current exceeding some max safe threshold, then we should probably shut off the battery heater and set `heater_status` to `HEATER_STATUS_FAULT`.

---

On a different note, what do you think about adding a timeout parameter to the heater command?  It could be a `uint8` where 0 means the heater request never times out, and any other value [1, 255] is the time in minutes that the heater will be enabled.

**Comment by tylerbrunette** [comment]
> On a different note, what do you think about adding a timeout parameter to the heater command? It could be a `uint8` where 0 means the heater request never times out, and any other value [1, 255] is the time in minutes that the heater will be enabled.

Seems like a good idea.

**Review by tylerbrunette — APPROVED** [review]

**Comment by jensenr30** [comment]
@tylerbrunette I added a timeout parameter to the heater command.

**Comment by tylerbrunette** [comment]
Functionality is fine, but you might want to adjust the formatting. Check some official messages like [BatteryInfo](https://github.com/botlink/DroneCAN_DSDL/blob/master/uavcan/equipment/power/1092.BatteryInfo.uavcan)

When you have constants for an enum or bitflags they should start with name of the variable, some tools use this when displaying the messages to convert the integers into strings.

Whitespace to seperate groups is always nice.

I'm not sure why you split that timeout comment into 2 lines, did your editor autoformat that?

Something like this:
```
#
# Service to enable and disable the battery heater
#

uint8 COMMAND_STOP              = 0 # Disable the battery heater
uint8 COMMAND_START_HEATING     = 1 # Enable the battery heater
uint8 COMMAND_DISMISS_FAULT     = 2 # Clear the fault status if able
uint8 command

int8 target_temperature  # [Deg. C] The battery will be heated up to this temperature

uint8 TIMEOUT_NONE   = 0 # The heater will stay on until a STOP command is received, or a FAULT occurs
uint8 timeout            # [Minutes] The heater will turn off after this amount of time

---

uint8 ERROR_OK      = 0   # Success
uint8 ERROR_UNKNOWN = 255 # Generic error
uint8 error
```

**Comment by jensenr30** [comment]
@tylerbrunette I will mimic the official message format from now on.  Thanks!

**Review by tylerbrunette — APPROVED** [review]

**Pull request merged**
